/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.consistent.transporte.service.model.impl;

import com.consistent.transporte.service.model.Grupos;
import com.consistent.transporte.service.model.GruposModel;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Grupos service. Represents a row in the &quot;Escuela_Grupos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>GruposModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GruposImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GruposImpl
 * @generated
 */
@ProviderType
public class GruposModelImpl
	extends BaseModelImpl<Grupos> implements GruposModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a grupos model instance should use the <code>Grupos</code> interface instead.
	 */
	public static final String TABLE_NAME = "Escuela_Grupos";

	public static final Object[][] TABLE_COLUMNS = {
		{"grupoId", Types.INTEGER}, {"nombre", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("grupoId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nombre", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Escuela_Grupos (grupoId INTEGER not null primary key,nombre VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Escuela_Grupos";

	public static final String ORDER_BY_JPQL = " ORDER BY grupos.grupoId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Escuela_Grupos.grupoId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public GruposModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _grupoId;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setGrupoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _grupoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Grupos.class;
	}

	@Override
	public String getModelClassName() {
		return Grupos.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Grupos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Grupos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Grupos, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Grupos)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Grupos, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Grupos, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Grupos)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Grupos, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Grupos, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Grupos>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Grupos.class.getClassLoader(), Grupos.class, ModelWrapper.class);

		try {
			Constructor<Grupos> constructor =
				(Constructor<Grupos>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Grupos, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Grupos, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Grupos, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Grupos, Object>>();
		Map<String, BiConsumer<Grupos, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Grupos, ?>>();

		attributeGetterFunctions.put("grupoId", Grupos::getGrupoId);
		attributeSetterBiConsumers.put(
			"grupoId", (BiConsumer<Grupos, Integer>)Grupos::setGrupoId);
		attributeGetterFunctions.put("nombre", Grupos::getNombre);
		attributeSetterBiConsumers.put(
			"nombre", (BiConsumer<Grupos, String>)Grupos::setNombre);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public int getGrupoId() {
		return _grupoId;
	}

	@Override
	public void setGrupoId(int grupoId) {
		_grupoId = grupoId;
	}

	@Override
	public String getNombre() {
		if (_nombre == null) {
			return "";
		}
		else {
			return _nombre;
		}
	}

	@Override
	public void setNombre(String nombre) {
		_nombre = nombre;
	}

	@Override
	public Grupos toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Grupos>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GruposImpl gruposImpl = new GruposImpl();

		gruposImpl.setGrupoId(getGrupoId());
		gruposImpl.setNombre(getNombre());

		gruposImpl.resetOriginalValues();

		return gruposImpl;
	}

	@Override
	public int compareTo(Grupos grupos) {
		int primaryKey = grupos.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Grupos)) {
			return false;
		}

		Grupos grupos = (Grupos)obj;

		int primaryKey = grupos.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Grupos> toCacheModel() {
		GruposCacheModel gruposCacheModel = new GruposCacheModel();

		gruposCacheModel.grupoId = getGrupoId();

		gruposCacheModel.nombre = getNombre();

		String nombre = gruposCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			gruposCacheModel.nombre = null;
		}

		return gruposCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Grupos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Grupos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Grupos, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Grupos)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Grupos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Grupos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Grupos, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Grupos)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Grupos>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private int _grupoId;
	private String _nombre;
	private Grupos _escapedModel;

}