/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.consistent.transporte.service.service.base;

import com.consistent.transporte.service.model.Grupos;
import com.consistent.transporte.service.service.GruposLocalService;
import com.consistent.transporte.service.service.persistence.AlumnosPersistence;
import com.consistent.transporte.service.service.persistence.EdificioPersistence;
import com.consistent.transporte.service.service.persistence.GruposPersistence;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.annotation.versioning.ProviderType;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the grupos local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.consistent.transporte.service.service.impl.GruposLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.consistent.transporte.service.service.impl.GruposLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class GruposLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements GruposLocalService, AopService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GruposLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.consistent.transporte.service.service.GruposLocalServiceUtil</code>.
	 */

	/**
	 * Adds the grupos to the database. Also notifies the appropriate model listeners.
	 *
	 * @param grupos the grupos
	 * @return the grupos that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Grupos addGrupos(Grupos grupos) {
		grupos.setNew(true);

		return gruposPersistence.update(grupos);
	}

	/**
	 * Creates a new grupos with the primary key. Does not add the grupos to the database.
	 *
	 * @param grupoId the primary key for the new grupos
	 * @return the new grupos
	 */
	@Override
	@Transactional(enabled = false)
	public Grupos createGrupos(int grupoId) {
		return gruposPersistence.create(grupoId);
	}

	/**
	 * Deletes the grupos with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param grupoId the primary key of the grupos
	 * @return the grupos that was removed
	 * @throws PortalException if a grupos with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Grupos deleteGrupos(int grupoId) throws PortalException {
		return gruposPersistence.remove(grupoId);
	}

	/**
	 * Deletes the grupos from the database. Also notifies the appropriate model listeners.
	 *
	 * @param grupos the grupos
	 * @return the grupos that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Grupos deleteGrupos(Grupos grupos) {
		return gruposPersistence.remove(grupos);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Grupos.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return gruposPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.consistent.transporte.service.model.impl.GruposModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return gruposPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.consistent.transporte.service.model.impl.GruposModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return gruposPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return gruposPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return gruposPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Grupos fetchGrupos(int grupoId) {
		return gruposPersistence.fetchByPrimaryKey(grupoId);
	}

	/**
	 * Returns the grupos with the primary key.
	 *
	 * @param grupoId the primary key of the grupos
	 * @return the grupos
	 * @throws PortalException if a grupos with the primary key could not be found
	 */
	@Override
	public Grupos getGrupos(int grupoId) throws PortalException {
		return gruposPersistence.findByPrimaryKey(grupoId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(gruposLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Grupos.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("grupoId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(gruposLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Grupos.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("grupoId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(gruposLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Grupos.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("grupoId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return gruposLocalService.deleteGrupos((Grupos)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return gruposPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the gruposes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>com.consistent.transporte.service.model.impl.GruposModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of gruposes
	 * @param end the upper bound of the range of gruposes (not inclusive)
	 * @return the range of gruposes
	 */
	@Override
	public List<Grupos> getGruposes(int start, int end) {
		return gruposPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of gruposes.
	 *
	 * @return the number of gruposes
	 */
	@Override
	public int getGruposesCount() {
		return gruposPersistence.countAll();
	}

	/**
	 * Updates the grupos in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param grupos the grupos
	 * @return the grupos that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Grupos updateGrupos(Grupos grupos) {
		return gruposPersistence.update(grupos);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GruposLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		gruposLocalService = (GruposLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GruposLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Grupos.class;
	}

	protected String getModelClassName() {
		return Grupos.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = gruposPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@Reference
	protected AlumnosPersistence alumnosPersistence;

	@Reference
	protected EdificioPersistence edificioPersistence;

	protected GruposLocalService gruposLocalService;

	@Reference
	protected GruposPersistence gruposPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}